// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct __swift_bridge__$RipgrepOptions { bool parallel; } __swift_bridge__$RipgrepOptions;
typedef struct __swift_bridge__$Option$RipgrepOptions { bool is_some; __swift_bridge__$RipgrepOptions val; } __swift_bridge__$Option$RipgrepOptions;
void* __swift_bridge__$ripgrep(void* term, struct __swift_bridge__$RipgrepOptions options);


